<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>TerrainCustomiserCNCollector</RootNamespace>
    <AssemblyName>TerrainCustomiserCNCollector</AssemblyName>
    <Version>0.1.1</Version>
    <LangVersion>latest</LangVersion>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>C:\Users\Administrator\AppData\Roaming\r2modmanPlus-local\PEAK\profiles\terrain\BepInEx\plugins\Snosz-TerrainCustomiserCN\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx">
      <HintPath>C:\Users\Administrator\AppData\Roaming\r2modmanPlus-local\PEAK\profiles\terrain\BepInEx\core\BepInEx.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>C:\SteamLibrary\steamapps\common\PEAK\PEAK_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\SteamLibrary\steamapps\common\PEAK\PEAK_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Users\Administrator\Desktop\MOD\PEAK\MOD开发\TerrainCustomiserCN\TerrainCustomiserCN\refs\Assembly-CSharp-publicized.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <ProjectReference Include="..\TerrainCustomiserCN\TerrainCustomiserCN.csproj" PrivateAssets="all" ReferenceOutputAssembly="true" OutputItemType="Reference" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Plugin.cs" />
  </ItemGroup>

</Project>
